---
version: '3'
services:
  database:
    image: postgres:10
    environment:
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/raw_data
      - ./sql:/sql
volumes:
  pgdata:
