---
version: '3'
services:
  database:
    build: .
    environment:
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./:/repo
volumes:
  pgdata:
